### ISSUE TITLE
cloudflare-edge-sdk docs/usage do not work, as written, with latest version of wrangler

### ISSUE THREAD

**Issue by dannyrb** [launchdarkly/cloudflare-edge-sdk#15]
**Describe the bug**
When the CloudFlare worker code executes, several issues arise:

- Wrangler complains of `node builtIns` usage. The CLI recommends adding the following to the `wrangler.toml`:

```toml
node_compat = true
```

- After adding the above config, the code is able to build successfully, but a new runtime exception is thrown for these lines:

```js
const ldClient = init(LD_KV_NAME, LD_CLIENT_SIDE_ID)
await ldClient.waitForInitialization()
```
_exception_
```
Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
```

**To reproduce**

1. Follow steps outline in [this Launchdarkly article](https://docs.launchdarkly.com/guides/infrastructure/cloudflare-workers#setting-up-a-project) with the latest version of `wrangler`
2. `npx wrangler dev`

**Expected behavior**
1. The LD Client should be able to initialize
2. The LD Client should not require opting out of `wrangler`'s default build
3. IF a separate build is required as a stop-gap, it should be clearly documented for the latest version of `wrangler`

**Logs**
If applicable, add any log output related to your problem.

**SDK version**
```
  "dependencies": {
    "launchdarkly-cloudflare-edge-sdk": "^1.0.0"
  },
  "devDependencies": {
    "@types/node": "^18.8.5",
    "typescript": "^4.8.4",
    "wrangler": "2.1.11"
  }
```

**Comment by ldhenry** [comment]
Hey @dannyrb,

Unfortunately `node_compat` does not do the trick because it doesn't pollyfill the `net` module as an empty object. I was able to get around this limitation by creating a custom build and using Webpack 4 to build the worker. The following steps worked for me:

1. Install `webpack`, `webpack-cli`, and add a build script to package.json:
```
{
  ...
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "@cloudflare/kv-asset-handler": "^0.2.0",
    "launchdarkly-cloudflare-edge-sdk": "^1.0.0"
  },
  "devDependencies": {
    "webpack": "4.46.0",
    "webpack-cli": "4.10.0",
  }
}
```

2. Added a `webpack.config.js` file with the following:
```
const path = require("path");

module.exports = {
  entry: "./index.js",
  target: "webworker",
  output: { path: path.resolve(__dirname, "worker"), filename: "script.js" },
  node: {
    fs: "empty",
    tls: "empty",
    net: "empty",
  },
};
```

3. Modified `wrangler.toml` with a [custom build](https://developers.cloudflare.com/workers/wrangler/configuration/#inheritable-keys):
```
main = "worker/script.js"
[build]
command = "npm run build"
``` 

Here is a sample repo with the complete setup:
https://github.com/launchdarkly/hello-cloudflare-react

In theory you should be able to use any bundler you want (esbuild, Webpack 5, etc) but I could only manage to get it working with Webpack 4 at this time.

I know this is not the ideal situation but I hope it unblocks you for the time being. Our SDK team is working on a version of the underlying node server SDK that does not require any pollyfills. Once available it should remove the need for a custom build.

Thanks,
Henry

**Comment by ldhenry** [comment]
Hey @dannyrb,

I updated our [Using LaunchDarkly with Cloudflare Workers](https://docs.launchdarkly.com/guides/infrastructure/cloudflare-workers) guide to be compatible with Wrangler 2 using a custom Webpack 4 build.

I'm going to close this issue for now, but feel free to reopen it if you run into any issues.

Thanks,
Henry
